version: "3.7"

services:
  web:
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: yarn start
    stdin_open: true
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
