version: 2.1

orbs:
  slack: circleci/slack@4.0.1

executors:
  default:
    docker:
      - image: node:16.0.0
    working_directory: ~/slc_app

jobs:
  install-and-build:
    executor: default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  unit-tests:
    executor: default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run: yarn test
      - slack/notify:
          event: fail
          template: basic_fail_1
  linting:
    executor: default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run:
          name: Code linting
          command: yarn run lint
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  version: 2
  push:
    jobs:
      - install-and-build:
          context:
            - SLC-Global
      - linting:
          context:
            - SLC-Global
          requires:
            - install-and-build
      - unit-tests:
          context:
            - SLC-Global
          requires:
            - install-and-build
